version: '3'
services:
  elasticsearch:
    platform: linux/amd64
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  db:
    platform: linux/x86_64
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5438:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    image: odoo:14.0
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data:
    driver: local
  web-data:
    driver: local