# Generated by Django 4.1.7 on 2023-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descrip_product', models.TextField()),
                ('img_product', models.CharField(max_length=200)),
                ('stock_product', models.BooleanField(null=True)),
            ],
        ),
    ]
